# Generated by Django 5.2.8 on 2025-11-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Careplus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
    ]
